'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BillInfor
    Public Property Id As Integer
    Public Property IdBill As Integer
    Public Property IdFood As Integer
    Public Property FoodCount As Integer

    Public Overridable Property Bill As Bill
    Public Overridable Property Food As Food

End Class
