'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bill
    Public Property Id As Integer
    Public Property DateCheckIn As Date
    Public Property IdTable As Integer
    Public Property DateCheckOut As Date
    Public Property TotalPrice As Double

    Public Overridable Property TableFood As TableFood
    Public Overridable Property BillInfors As ICollection(Of BillInfor) = New HashSet(Of BillInfor)

End Class
