'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M_CODE
    Public Property CD_SYU As String
    Public Property CD_NO As Decimal
    Public Property CD_NAME As String
    Public Property CD_RYAKU As String
    Public Property UPD_DATE As Nullable(Of Date)
    Public Property UPD_TIME As String
    Public Property UPD_TANTO As String

End Class
