'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M_IRYOKIKAN
    Public Property IRYO_KIKAN_CD As Decimal
    Public Property IRYO_NAME_KJ As String
    Public Property IRYO_NAME_KN As String
    Public Property POST As String
    Public Property ADDRESS1 As String
    Public Property ADDRESS2 As String
    Public Property TEL1 As String
    Public Property TEL2 As String
    Public Property FAX As String
    Public Property HAISI_KBN As Nullable(Of Decimal)
    Public Property HAISI_DATE As Nullable(Of Date)
    Public Property UPD_DATE As Nullable(Of Date)
    Public Property UPD_TIME As String
    Public Property UPD_TANTO As String
    Public Property SORT_KN As String
    Public Property IRYO_EM As String
    Public Property IRYO_URL As String
    Public Property IRYO_CARD_40 As Nullable(Of Decimal)
    Public Property IRYO_CARD_NIN As Nullable(Of Decimal)

End Class
