'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M_SCH_KAIHI
    Public Property SCH_KAIHI_KBN As Decimal
    Public Property KAIHI As Nullable(Of Decimal)
    Public Property UPD_DATE As Nullable(Of Date)
    Public Property UPD_TIME As String
    Public Property UPD_TANTO As String

End Class
