'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class QuanCafeEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=QuanCafeEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Accounts() As DbSet(Of Account)
    Public Overridable Property Bills() As DbSet(Of Bill)
    Public Overridable Property BillInfors() As DbSet(Of BillInfor)
    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property Foods() As DbSet(Of Food)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property TableFoods() As DbSet(Of TableFood)
    Public Overridable Property M_POST() As DbSet(Of M_POST)
    Public Overridable Property M_SCH_KAIHI() As DbSet(Of M_SCH_KAIHI)
    Public Overridable Property M_CODE() As DbSet(Of M_CODE)

End Class
