'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TableFood
    Public Property Id As Integer
    Public Property Name As String
    Public Property Status As Nullable(Of Boolean)

    Public Overridable Property Bills As ICollection(Of Bill) = New HashSet(Of Bill)

End Class
